"""Frozen, forme-keyed gen-4 vocabularies (embedding row indices; row 0 = unknown).

Generated by scripts/gen4_build_vocab.py from the vendored randbats pool at
the Showdown commit stamped inside data/gen4_vocab.json. Keys are poke-env's
own id strings: `Pokemon.species` (forme ids — Arceus-Ghost and Arceus-Water
are different rows, unlike dex `num`), `Move.id` (typed Hidden Power ids —
all 17 share `num` 237), `Pokemon.ability`, `Pokemon.item`. Anything
outside the tables maps to 0, exactly as an out-of-range `num` does in gen 1;
a Showdown bump that adds a set entry is a pre-reg pin violation, not a
silent feature change (docs/design_gen4/encoder_requirements.md §3.2).
"""

from __future__ import annotations

import json
import re
from functools import lru_cache
from pathlib import Path

DATA_DIR = Path(__file__).with_name("data")
VOCAB_PATH = DATA_DIR / "gen4_vocab.json"

_NON_ID = re.compile(r"[^a-z0-9]")
# The RAW request names Return / Frustration with their happiness base power
# ("Return 102" -> `return102` in `side.pokemon[].moves`; measured on 18,535
# request moves). poke-env's own Move objects already read `return`
# (Move.retrieve_id strips the suffix, as it strips Hidden Power's type), so
# this normaliser matters for raw ids only: the vocab builder, the tape
# statistics and anything else reading the request JSON directly.
_HAPPINESS_MOVE = re.compile(r"^(return|frustration)\d+$")


def to_id(name: str | None) -> str:
    """Showdown's toID: lowercase, alphanumerics only ('Sand Stream' -> 'sandstream')."""
    return _NON_ID.sub("", (name or "").lower())


def canonical_move_id(move_id: str | None) -> str:
    """A move id with the happiness power suffix removed (`return102` ->
    `return`), the key the vocab, the prior and the effect block use. A no-op
    on poke-env's Move.id (already stripped); load-bearing on raw request ids."""
    mid = to_id(move_id)
    m = _HAPPINESS_MOVE.match(mid)
    return m.group(1) if m else mid


@lru_cache(maxsize=1)
def raw() -> dict:
    with VOCAB_PATH.open() as fh:
        return json.load(fh)


class Vocab:
    """Four id tables with 1-based rows (0 = unknown / unrevealed / none)."""

    def __init__(self, data: dict):
        self.showdown_commit: str = data["showdown_commit"]
        self.sets_sha256: str = data["sets_sha256"]
        self.species: tuple[str, ...] = tuple(data["species"])
        self.moves: tuple[str, ...] = tuple(data["moves"])
        self.abilities: tuple[str, ...] = tuple(data["abilities"])
        self.items: tuple[str, ...] = tuple(data["items"])
        self.levels: dict[str, int] = dict(data["levels"])
        self._species = {s: i + 1 for i, s in enumerate(self.species)}
        self._moves = {m: i + 1 for i, m in enumerate(self.moves)}
        self._abilities = {a: i + 1 for i, a in enumerate(self.abilities)}
        self._items = {it: i + 1 for i, it in enumerate(self.items)}

    # sizes INCLUDING row 0 — what an embedding table must be built with
    @property
    def n_species(self) -> int:
        return len(self.species) + 1

    @property
    def n_moves(self) -> int:
        return len(self.moves) + 1

    @property
    def n_abilities(self) -> int:
        return len(self.abilities) + 1

    @property
    def n_items(self) -> int:
        return len(self.items) + 1

    def species_id(self, species: str | None) -> int:
        return self._species.get(to_id(species), 0)

    def move_id(self, move_id: str | None) -> int:
        return self._moves.get(canonical_move_id(move_id), 0)

    def ability_id(self, ability: str | None) -> int:
        return self._abilities.get(to_id(ability), 0)

    def item_id(self, item: str | None) -> int:
        """0 for None / '' / 'unknown_item' (poke-env's three falsy-but-distinct
        item states — the STATE is encoded separately, this is identity only)."""
        if not item or item == "unknown_item":
            return 0
        return self._items.get(to_id(item), 0)


VOCAB = Vocab(raw())
