/* automatically generated by rust-bindgen 0.72.1 */

pub const PKMN_PSRNG_SIZE: u32 = 8;
pub const PKMN_RATIONAL_SIZE: u32 = 16;
pub const PKMN_GEN1_BATTLE_SIZE: u32 = 384;
pub const PKMN_GEN1_BATTLE_OPTIONS_SIZE: u32 = 128;
pub const PKMN_GEN1_CHANCE_ACTIONS_SIZE: u32 = 16;
pub const PKMN_GEN1_CHANCE_DURATIONS_SIZE: u32 = 8;
pub const PKMN_GEN1_CALC_OVERRIDES_SIZE: u32 = 24;
pub const PKMN_GEN1_CALC_SUMMARIES_SIZE: u32 = 8;
pub type float64_t = f64;
#[doc = " Compile time options acknowledged by libpkmn."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pkmn_options {
    pub showdown: bool,
    pub log: bool,
    pub chance: bool,
    pub calc: bool,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pkmn_options"][::std::mem::size_of::<pkmn_options>() - 4usize];
    ["Alignment of pkmn_options"][::std::mem::align_of::<pkmn_options>() - 1usize];
    ["Offset of field: pkmn_options::showdown"]
        [::std::mem::offset_of!(pkmn_options, showdown) - 0usize];
    ["Offset of field: pkmn_options::log"][::std::mem::offset_of!(pkmn_options, log) - 1usize];
    ["Offset of field: pkmn_options::chance"]
        [::std::mem::offset_of!(pkmn_options, chance) - 2usize];
    ["Offset of field: pkmn_options::calc"][::std::mem::offset_of!(pkmn_options, calc) - 3usize];
};
unsafe extern "C" {
    #[doc = " Compile time options set when libpkmn was built."]
    pub static PKMN_OPTIONS: pkmn_options;
}
unsafe extern "C" {
    #[doc = " The minimum size in bytes required to hold all choice options."]
    pub static PKMN_MAX_CHOICES: usize;
}
unsafe extern "C" {
    #[doc = " The optimal size in bytes required to hold all choice options. At least as\n large as PKMN_MAX_CHOICES."]
    pub static PKMN_CHOICES_SIZE: usize;
}
unsafe extern "C" {
    #[doc = " The maximum number of bytes possibly logged by a single update."]
    pub static PKMN_MAX_LOGS: usize;
}
unsafe extern "C" {
    #[doc = " The optimal size in bytes required to hold the largest amount of log data\n possible from a single update. At least as large as PKMN_MAX_LOGS."]
    pub static PKMN_LOGS_SIZE: usize;
}
pub const PKMN_PLAYER_P1: pkmn_player = 0;
pub const PKMN_PLAYER_P2: pkmn_player = 1;
#[doc = " Identifier for a single player."]
pub type pkmn_player = ::std::os::raw::c_uint;
#[doc = " A choice made by a player."]
pub type pkmn_choice = u8;
pub const PKMN_CHOICE_PASS: pkmn_choice_kind = 0;
pub const PKMN_CHOICE_MOVE: pkmn_choice_kind = 1;
pub const PKMN_CHOICE_SWITCH: pkmn_choice_kind = 2;
#[doc = " The type of choice."]
pub type pkmn_choice_kind = ::std::os::raw::c_uchar;
unsafe extern "C" {
    #[doc = " Returns a choice initialized for a specific type with the provided data.\n data must be <= 6."]
    pub fn pkmn_choice_init(type_: pkmn_choice_kind, data: u8) -> pkmn_choice;
}
unsafe extern "C" {
    #[doc = " The choice type of the choice."]
    pub fn pkmn_choice_type(choice: pkmn_choice) -> pkmn_choice_kind;
}
unsafe extern "C" {
    #[doc = " The choice data of the choice."]
    pub fn pkmn_choice_data(choice: pkmn_choice) -> u8;
}
#[doc = " The result of updating a battle."]
pub type pkmn_result = u8;
pub const PKMN_RESULT_NONE: pkmn_result_kind = 0;
pub const PKMN_RESULT_WIN: pkmn_result_kind = 1;
pub const PKMN_RESULT_LOSE: pkmn_result_kind = 2;
pub const PKMN_RESULT_TIE: pkmn_result_kind = 3;
pub const PKMN_RESULT_ERROR: pkmn_result_kind = 4;
#[doc = " The type of result."]
pub type pkmn_result_kind = ::std::os::raw::c_uchar;
unsafe extern "C" {
    #[doc = " The result type of the result."]
    pub fn pkmn_result_type(result: pkmn_result) -> pkmn_result_kind;
}
unsafe extern "C" {
    #[doc = " The choice type of the result for Player 1."]
    pub fn pkmn_result_p1(result: pkmn_result) -> pkmn_choice_kind;
}
unsafe extern "C" {
    #[doc = " The choice type of the result for Player 2."]
    pub fn pkmn_result_p2(result: pkmn_result) -> pkmn_choice_kind;
}
unsafe extern "C" {
    #[doc = " Whether or not the update resulted in an error being thrown. This can only\n happen if libpkmn was built with protocol message logging enabled and the\n buffer provided to the update function was not large enough to hold all of\n the data (which is only possible if the buffer being used was smaller than\n generation in question's MAX_LOGS bytes)."]
    pub fn pkmn_error(result: pkmn_result) -> bool;
}
#[doc = " Pokémon Showdown's RNG (backed by a Generation V & VI RNG)."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pkmn_psrng {
    pub bytes: [u8; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pkmn_psrng"][::std::mem::size_of::<pkmn_psrng>() - 8usize];
    ["Alignment of pkmn_psrng"][::std::mem::align_of::<pkmn_psrng>() - 1usize];
    ["Offset of field: pkmn_psrng::bytes"][::std::mem::offset_of!(pkmn_psrng, bytes) - 0usize];
};
unsafe extern "C" {
    #[doc = " Initialize the Pokémon Showdown RNG with the given seed."]
    pub fn pkmn_psrng_init(psrng: *mut pkmn_psrng, seed: u64);
}
unsafe extern "C" {
    #[doc = " Returns the next number produced by the Pokémon Showdown RNG and advances the seed."]
    pub fn pkmn_psrng_next(psrng: *mut pkmn_psrng) -> u32;
}
#[doc = " Specialization of a rational number used by the engine to compute probabilties.\n For performance reasons the rational is only reduced lazily and thus reduce\n must be invoked explicitly before reading."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pkmn_rational {
    pub bytes: [u8; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pkmn_rational"][::std::mem::size_of::<pkmn_rational>() - 16usize];
    ["Alignment of pkmn_rational"][::std::mem::align_of::<pkmn_rational>() - 1usize];
    ["Offset of field: pkmn_rational::bytes"]
        [::std::mem::offset_of!(pkmn_rational, bytes) - 0usize];
};
unsafe extern "C" {
    #[doc = " Initializes (or resets) the rational to 1."]
    pub fn pkmn_rational_init(rational: *mut pkmn_rational);
}
unsafe extern "C" {
    #[doc = " Normalize the rational by reducing by the greatest common divisor."]
    pub fn pkmn_rational_reduce(rational: *mut pkmn_rational);
}
unsafe extern "C" {
    #[doc = " Returns the numerator of the rational."]
    pub fn pkmn_rational_numerator(rational: *const pkmn_rational) -> float64_t;
}
unsafe extern "C" {
    #[doc = " Returns the denominator of the rational."]
    pub fn pkmn_rational_denominator(rational: *const pkmn_rational) -> float64_t;
}
unsafe extern "C" {
    #[doc = " The minimum size in bytes required to hold the all Generation I choice options."]
    pub static PKMN_GEN1_MAX_CHOICES: usize;
}
unsafe extern "C" {
    #[doc = " The optimal size in bytes required to hold the all Generation I choice\n options. At least as large as PKMN_GEN1_MAX_CHOICES."]
    pub static PKMN_GEN1_CHOICES_SIZE: usize;
}
unsafe extern "C" {
    #[doc = " The maximum number of bytes possibly logged by a single Generation I update."]
    pub static PKMN_GEN1_MAX_LOGS: usize;
}
unsafe extern "C" {
    #[doc = " The optimal size in bytes required to hold the largest amount of log data\n possible from a single Generation I update. At least as large as\n PKMN_GEN1_MAX_LOGS."]
    pub static PKMN_GEN1_LOGS_SIZE: usize;
}
#[doc = " Generation I Pokémon Battle (see src/lib/gen1/README.md#layout for details)."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pkmn_gen1_battle {
    pub bytes: [u8; 384usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pkmn_gen1_battle"][::std::mem::size_of::<pkmn_gen1_battle>() - 384usize];
    ["Alignment of pkmn_gen1_battle"][::std::mem::align_of::<pkmn_gen1_battle>() - 1usize];
    ["Offset of field: pkmn_gen1_battle::bytes"]
        [::std::mem::offset_of!(pkmn_gen1_battle, bytes) - 0usize];
};
#[doc = " Generation I Pokémon Battle options (fully opaque - uses getters to access)."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pkmn_gen1_battle_options {
    pub bytes: [u8; 128usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pkmn_gen1_battle_options"]
        [::std::mem::size_of::<pkmn_gen1_battle_options>() - 128usize];
    ["Alignment of pkmn_gen1_battle_options"]
        [::std::mem::align_of::<pkmn_gen1_battle_options>() - 1usize];
    ["Offset of field: pkmn_gen1_battle_options::bytes"]
        [::std::mem::offset_of!(pkmn_gen1_battle_options, bytes) - 0usize];
};
#[doc = " Generation I Pokémon chance actions (see src/lib/gen1/README.md#layout for details)."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pkmn_gen1_chance_actions {
    pub bytes: [u8; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pkmn_gen1_chance_actions"]
        [::std::mem::size_of::<pkmn_gen1_chance_actions>() - 16usize];
    ["Alignment of pkmn_gen1_chance_actions"]
        [::std::mem::align_of::<pkmn_gen1_chance_actions>() - 1usize];
    ["Offset of field: pkmn_gen1_chance_actions::bytes"]
        [::std::mem::offset_of!(pkmn_gen1_chance_actions, bytes) - 0usize];
};
#[doc = " Generation I Pokémon chance durations (see src/lib/gen1/README.md#layout for details)."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pkmn_gen1_chance_durations {
    pub bytes: [u8; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pkmn_gen1_chance_durations"]
        [::std::mem::size_of::<pkmn_gen1_chance_durations>() - 8usize];
    ["Alignment of pkmn_gen1_chance_durations"]
        [::std::mem::align_of::<pkmn_gen1_chance_durations>() - 1usize];
    ["Offset of field: pkmn_gen1_chance_durations::bytes"]
        [::std::mem::offset_of!(pkmn_gen1_chance_durations, bytes) - 0usize];
};
#[doc = " Generation I Pokémon calc overrides (see src/lib/gen1/README.md#layout for details)."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pkmn_gen1_calc_overrides {
    pub bytes: [u8; 24usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pkmn_gen1_calc_overrides"]
        [::std::mem::size_of::<pkmn_gen1_calc_overrides>() - 24usize];
    ["Alignment of pkmn_gen1_calc_overrides"]
        [::std::mem::align_of::<pkmn_gen1_calc_overrides>() - 1usize];
    ["Offset of field: pkmn_gen1_calc_overrides::bytes"]
        [::std::mem::offset_of!(pkmn_gen1_calc_overrides, bytes) - 0usize];
};
#[doc = " Generation I Pokémon calc summaries (see src/lib/gen1/README.md#layout for details)."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pkmn_gen1_calc_summaries {
    pub bytes: [u8; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pkmn_gen1_calc_summaries"]
        [::std::mem::size_of::<pkmn_gen1_calc_summaries>() - 8usize];
    ["Alignment of pkmn_gen1_calc_summaries"]
        [::std::mem::align_of::<pkmn_gen1_calc_summaries>() - 1usize];
    ["Offset of field: pkmn_gen1_calc_summaries::bytes"]
        [::std::mem::offset_of!(pkmn_gen1_calc_summaries, bytes) - 0usize];
};
#[doc = " Provides a buffer buf of length len to store protocol message logs if\n protocol logging is enabled (see docs/PROTOCOL.md). This buffer should be\n reset by calling pkmn_gen1_battle_options_set with NULL provided as the\n second argument after each update."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pkmn_gen1_log_options {
    pub buf: *mut u8,
    pub len: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pkmn_gen1_log_options"][::std::mem::size_of::<pkmn_gen1_log_options>() - 16usize];
    ["Alignment of pkmn_gen1_log_options"]
        [::std::mem::align_of::<pkmn_gen1_log_options>() - 8usize];
    ["Offset of field: pkmn_gen1_log_options::buf"]
        [::std::mem::offset_of!(pkmn_gen1_log_options, buf) - 0usize];
    ["Offset of field: pkmn_gen1_log_options::len"]
        [::std::mem::offset_of!(pkmn_gen1_log_options, len) - 8usize];
};
#[doc = " Provides the probability and chance actions and duration counters necessary\n for tracking chance outcomes during a Generation I battle update if chance\n tracking is enabled."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pkmn_gen1_chance_options {
    pub probability: pkmn_rational,
    pub actions: pkmn_gen1_chance_actions,
    pub durations: pkmn_gen1_chance_durations,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pkmn_gen1_chance_options"]
        [::std::mem::size_of::<pkmn_gen1_chance_options>() - 40usize];
    ["Alignment of pkmn_gen1_chance_options"]
        [::std::mem::align_of::<pkmn_gen1_chance_options>() - 1usize];
    ["Offset of field: pkmn_gen1_chance_options::probability"]
        [::std::mem::offset_of!(pkmn_gen1_chance_options, probability) - 0usize];
    ["Offset of field: pkmn_gen1_chance_options::actions"]
        [::std::mem::offset_of!(pkmn_gen1_chance_options, actions) - 16usize];
    ["Offset of field: pkmn_gen1_chance_options::durations"]
        [::std::mem::offset_of!(pkmn_gen1_chance_options, durations) - 32usize];
};
#[doc = " Overrides to apply to the normal behavior of the RNG during a Generation I\n battle `update` if damage calculation support is enabled."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pkmn_gen1_calc_options {
    pub overrides: pkmn_gen1_calc_overrides,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pkmn_gen1_calc_options"][::std::mem::size_of::<pkmn_gen1_calc_options>() - 24usize];
    ["Alignment of pkmn_gen1_calc_options"]
        [::std::mem::align_of::<pkmn_gen1_calc_options>() - 1usize];
    ["Offset of field: pkmn_gen1_calc_options::overrides"]
        [::std::mem::offset_of!(pkmn_gen1_calc_options, overrides) - 0usize];
};
unsafe extern "C" {
    #[doc = " Set or reset the Generation I battle options struct based on the log, chance,\n and calc options provided. This function should usually be called before each\n battle update first to initialize the battle options and then on subsequent\n calls to \"reset\" the same struct so that it can be reused. Resets are\n accomplished by passing NULL for any argument after the first."]
    pub fn pkmn_gen1_battle_options_set(
        options: *mut pkmn_gen1_battle_options,
        log: *const pkmn_gen1_log_options,
        chance: *const pkmn_gen1_chance_options,
        calc: *const pkmn_gen1_calc_options,
    );
}
unsafe extern "C" {
    #[doc = " Returns a pointer to a pkmn_rational containing the probability of the\n actions taken by a hypothetical \"chance player\" occuring during a Generation\n I battle update."]
    pub fn pkmn_gen1_battle_options_chance_probability(
        options: *const pkmn_gen1_battle_options,
    ) -> *mut pkmn_rational;
}
unsafe extern "C" {
    #[doc = " Returns a pointer to the actions taken by a hypothetical \"chance player\"\n that convey information about which RNG events were observed during a\n Generation I battle update."]
    pub fn pkmn_gen1_battle_options_chance_actions(
        options: *const pkmn_gen1_battle_options,
    ) -> *mut pkmn_gen1_chance_actions;
}
unsafe extern "C" {
    #[doc = " Returns a pointer to the duration counters tracking the information required\n to compute the observed probabilities of \"chance player\" actions during a\n Generation I battle update."]
    pub fn pkmn_gen1_battle_options_chance_durations(
        options: *const pkmn_gen1_battle_options,
    ) -> *mut pkmn_gen1_chance_durations;
}
unsafe extern "C" {
    #[doc = " Returns a pointer to information relevant to damage calculation that occured\n during a Generation I battle update."]
    pub fn pkmn_gen1_battle_options_calc_summaries(
        options: *const pkmn_gen1_battle_options,
    ) -> *mut pkmn_gen1_calc_summaries;
}
unsafe extern "C" {
    #[doc = " Returns the result of applying Player 1's choice c1 and Player 2's choice c2\n to the Generation I battle. If the options argument is not NULL and the\n relevant additional features are enabled it will be used to track additional\n information about what happened during the update."]
    pub fn pkmn_gen1_battle_update(
        battle: *mut pkmn_gen1_battle,
        c1: pkmn_choice,
        c2: pkmn_choice,
        options: *mut pkmn_gen1_battle_options,
    ) -> pkmn_result;
}
unsafe extern "C" {
    #[doc = " Fills in out with at most len possible choices for the player given the\n request and Generation I battle state and returns the number of choices\n available. Note that reading values in out which occur at indexes > the\n return value of this function could result in reading potentially garbage\n data.\n\n This function may return 0 due to how the Transform + Mirror Move/Metronome\n PP error interacts with Disable, in which case there are no possible choices\n for the player to make (i.e. on the cartridge a soft-lock occurs).\n\n This function will always return a number of choices > 0 if\n PKMN_CHOICES.showdown is true."]
    pub fn pkmn_gen1_battle_choices(
        battle: *const pkmn_gen1_battle,
        player: pkmn_player,
        request: pkmn_choice_kind,
        out: *mut pkmn_choice,
        len: usize,
    ) -> u8;
}
