"""Reproducible power/size tables for the CH3 R5 pre-registrations.

    python scripts/ch3_r5_power_sim.py --tgate
    python scripts/ch3_r5_power_sim.py --primary
    python scripts/ch3_r5_power_sim.py --placebo

Moved from results/design_critic/r5_power_sim.py at ratification
(2026-08-24, per its own note); --placebo adds the Q8 false-strike cells
the r5b pre-reg quotes (they were computed in the design cycle but the
committed script owed the function).

Both tables in ch3_r5a_tgate_draft.yaml (Q3) and ch3_r5b_exit_draft.yaml
(Q7) are generated by THIS script and by nothing else; the pre-regs quote
its output verbatim. At ratification this file moves to
scripts/ch3_r5_power_sim.py and its cells are pinned in the graders'
--selftest (review 1 finding 14: "regenerate the table from a committed
script and pin it in --selftest").

se law, both tables: scripts/ch3_r2_grade.se_terms_r2 UNMODIFIED — the
larger of {pooled-binomial two-sample, paired-clustered sd(d)/sqrt(k),
unpaired two-sample clustered}. No t-multiplier is used anywhere; the
credit line is a fixed 2*se.
"""

import argparse
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
from ch3_r2_grade import FLOOR, se_terms_r2  # noqa: E402

RNG = np.random.default_rng(20260824)


# --------------------------------------------------------------------------
# STAGE 1 — the T-GATE (ch3_r5a)
# --------------------------------------------------------------------------
# EXACT SIMULATION RULE, stated so the table is reproducible:
#   k = 4 lanes. Per rep:
#     mu_i   = mu + N(0, lane_sd)                       true per-lane margin
#     q0_i   = 0.50                                     true T_M rate (mirror;
#                                                       0.50 maximises the
#                                                       binomial variance =
#                                                       the conservative choice)
#     q1_i   = q0_i + mu_i                              true T_S rate
#     qhat_i = Binomial(n, q_i) / n                     observed, both arms
#     m_i    = qhat1_i - qhat0_i ; mean = mean(m_i)
#     se_gov = se_terms_r2(qhat1, qhat0, n)["se_gov"]   larger-of-THREE
#     L = mean - 2*se_gov ; U = mean + 2*se_gov ; kpos = #{m_i > 0}
#   CELLS (total, disjoint, evaluated in this order):
#     T-PASS       : U >= 0.05 AND L > 0 AND kpos >= 3
#     T-FAIL       : U <  0.05
#     T-UNRESOLVED : otherwise
def tgate_cells(n: int, mu: float, lane_sd: float, reps: int, thresh: float = 0.05):
    mu_i = mu + RNG.normal(0.0, lane_sd, size=(reps, 4)) if lane_sd else np.full((reps, 4), mu)
    q0 = np.full((reps, 4), 0.50)
    q1 = np.clip(q0 + mu_i, 1e-6, 1 - 1e-6)
    h0 = RNG.binomial(n, q0) / n
    h1 = RNG.binomial(n, q1) / n
    m = h1 - h0
    mean = m.mean(axis=1)
    se = np.empty(reps)
    for r in range(reps):
        se[r] = se_terms_r2(list(h1[r]), list(h0[r]), n)["se_gov"]
    lo, hi = mean - 2 * se, mean + 2 * se
    kpos = (m > 0).sum(axis=1)
    p = (hi >= thresh) & (lo > 0) & (kpos >= 3)
    f = hi < thresh
    return p.mean(), f.mean(), 1.0 - p.mean() - f.mean()


def tgate_table(reps: int = 40000) -> None:
    print("STAGE-1 T-GATE operating characteristics "
          f"(reps={reps}, threshold 0.05, se = larger-of-three)")
    for n in (500, 750, 1000, 1500):
        print(f"\n  n = {n} battles per arm per lane")
        print("    true margin |  P(T-PASS)  P(T-UNRESOLVED)  P(T-FAIL)")
        for lane_sd in (0.0, 0.02):
            print(f"    -- lane sd {lane_sd:.2f} --")
            for mu in (0.00, 0.03, 0.05, 0.07):
                pp, pf, pu = tgate_cells(n, mu, lane_sd, reps)
                print(f"    {mu:+.2f}        |   {pp:.3f}        {pu:.3f}          {pf:.3f}")


# --------------------------------------------------------------------------
# STAGE 2 — the primary credit read (ch3_r5b)
# --------------------------------------------------------------------------
# EXACT SIMULATION RULE:
#   k = 4 lanes, n = 3000 battles per lane per arm. Per rep:
#     p0_i = N(0.72, s_C)      s_C = the LANE-LEVEL spread of a fresh
#                              re-measurement of the four D26 finals; planning
#                              value = the WORST of the three fresh reads on
#                              disk (R3, 0.0199), not D26's training-era 0.011177
#     d_i  = N(mu, sd_d) ; p1_i = p0_i + d_i
#     phat = Binomial(n, p)/n for both arms
#     delta  = mean(phat1 - phat0)
#     se_gov = se_terms_r2(phat1, phat0, n)["se_gov"]
#     CREDIT iff delta >= max(0.025, 2*se_gov)      <- the credit line exactly
#   The SIZE row is P(CREDIT | mu = 0) and is REPORTED, never bounded by a
#   claim the rule does not honour (review 1 finding 14b).
def primary_credit(mu: float, sd_d: float, s_C: float, reps: int, n: int = 3000):
    p0 = np.clip(RNG.normal(0.72, s_C, size=(reps, 4)), 1e-6, 1 - 1e-6)
    d = RNG.normal(mu, sd_d, size=(reps, 4)) if sd_d else np.full((reps, 4), mu)
    p1 = np.clip(p0 + d, 1e-6, 1 - 1e-6)
    h0 = RNG.binomial(n, p0) / n
    h1 = RNG.binomial(n, p1) / n
    delta = (h1 - h0).mean(axis=1)
    cred = np.empty(reps, dtype=bool)
    cell_b5 = np.empty(reps, dtype=bool)
    cell_b3 = np.empty(reps, dtype=bool)
    for r in range(reps):
        se = se_terms_r2(list(h1[r]), list(h0[r]), n)["se_gov"]
        bar = max(FLOOR, 2 * se)
        cred[r] = delta[r] >= bar
        cell_b5[r] = delta[r] <= -bar
        cell_b3[r] = abs(delta[r]) < FLOOR
    return cred.mean(), cell_b3.mean(), cell_b5.mean()


def primary_table(reps: int = 40000) -> None:
    for s_C in (0.0199, 0.011177):
        print(f"\nPRIMARY P(CREDIT), k=4, n=3000, s_C = {s_C} (reps={reps})")
        print("    mu     | sd_d=.010   .016    .025    .035")
        for mu in (0.000, 0.020, 0.028, 0.030, 0.040, 0.055):
            row = [primary_credit(mu, sd, s_C, reps)[0] for sd in (0.010, 0.016, 0.025, 0.035)]
            tag = "  (SIZE)" if mu == 0.0 else ""
            print(f"    {mu:+.3f} |  " + "   ".join(f"{x:.3f}" for x in row) + tag)
    print("\nCELL PROBABILITIES at the pre-registered point mu=+0.028, "
          "s_C=0.0199:")
    for sd in (0.010, 0.016, 0.025, 0.035):
        c, b3, b5 = primary_credit(0.028, sd, 0.0199, reps)
        print(f"    sd_d={sd:.3f}: P(credit) {c:.3f} | P(B3) {b3:.3f} | P(B5) {b5:.3f}")
    print("\nP(B5) at mu = 0.000 and mu = -0.010, s_C=0.0199:")
    for mu in (0.000, -0.010):
        for sd in (0.016, 0.025):
            _, _, b5 = primary_credit(mu, sd, 0.0199, reps)
            print(f"    mu={mu:+.3f} sd_d={sd:.3f}: P(B5) {b5:.3f}")


def placebo_false_strike(sd_d: float, reps: int, s_C: float = 0.0199,
                         n: int = 3000, delta_x1: float = 0.028):
    """Q8: a TRULY NULL placebo (mu_PL = 0) against the paired fresh X0,
    strike threshold 0.6 * delta(X1) = 0.0168, same larger-of-three se law.
    Returns (P(PL-STRIKE), P(PL-UNCONFIRMED))."""
    thresh = 0.6 * delta_x1
    p0 = np.clip(RNG.normal(0.72, s_C, size=(reps, 4)), 1e-6, 1 - 1e-6)
    d = RNG.normal(0.0, sd_d, size=(reps, 4)) if sd_d else np.zeros((reps, 4))
    ppl = np.clip(p0 + d, 1e-6, 1 - 1e-6)
    h0 = RNG.binomial(n, p0) / n
    hpl = RNG.binomial(n, ppl) / n
    delta = (hpl - h0).mean(axis=1)
    strike = np.empty(reps, dtype=bool)
    unconf = np.empty(reps, dtype=bool)
    for r in range(reps):
        se = se_terms_r2(list(hpl[r]), list(h0[r]), n)["se_gov"]
        strike[r] = delta[r] >= thresh and delta[r] >= 2 * se
        unconf[r] = delta[r] >= thresh and delta[r] < 2 * se
    return strike.mean(), unconf.mean()


def placebo_table(reps: int = 40000) -> None:
    print("Q8 FALSE-STRIKE under a TRULY NULL placebo, delta(X1)=+0.028 "
          f"(threshold 0.0168), s_C=0.0199 (reps={reps}):")
    for sd in (0.010, 0.016, 0.025):
        st, un = placebo_false_strike(sd, reps)
        print(f"    sd_d={sd:.3f}: P(PL-STRIKE) {st:.3f} | "
              f"P(PL-UNCONFIRMED) {un:.3f}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tgate", action="store_true")
    ap.add_argument("--primary", action="store_true")
    ap.add_argument("--placebo", action="store_true")
    ap.add_argument("--reps", type=int, default=40000)
    a = ap.parse_args()
    if a.tgate:
        tgate_table(a.reps)
    if a.primary:
        primary_table(a.reps)
    if a.placebo:
        placebo_table(a.reps)


if __name__ == "__main__":
    main()
