#!/usr/bin/env python
"""LADDER R1 final readout — all three pre-registered obligations, in one pass.

WHY THIS WRITES MARKDOWN. `results/` is gitignored with zero tracked files, so
the JSONL and the 200+ replays live on disk and in mirrors but NEVER in git.
The same lesson `scripts/README.md` records for grader scripts applies harder
here: this script plus its committed output are the only provenance that
survives losing every copy of `results/ladder/`. Run it, commit the markdown.

The three obligations, all written result-blind during the run:
  (i)   rating trajectory rebuilt from the replays, because poke-env
        sporadically drops `battle.rating`;
  (ii)  the rematch cell WITH each cell's opponent-rating distribution,
        because rematches are rating-matched by construction and that
        confound reads exactly like the effect;
  (iii) played games vs non-games, classified from replay TEXT and behaviour
        (see ladder_classify.py for the amended rule).

JOIN TRAPS, both live: battle tags may carry a secret `-<token>` suffix, so
join on the NUMERIC id; and local-smoke replays share the real
`nickgen1rbrlbot` filename prefix, so filter by id WIDTH (real = 10 digits).
"""
import argparse, json, re, statistics, sys, collections
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
REAL_ID = re.compile(r"gen1randombattle-(\d{9,})")
ANY_ID = re.compile(r"gen1randombattle-(\d+)")


def load(jsonl, repdir, name):
    rows = [json.loads(l) for l in open(jsonl) if l.strip()]
    reps = {}
    for p in Path(repdir).glob("*.html"):
        m = REAL_ID.search(p.name)
        if m:
            reps[m.group(1)] = p.read_text(errors="ignore")
    for r in rows:
        r["_id"] = ANY_ID.search(r["tag"]).group(1)
        t = reps.get(r["_id"], "")
        r["_text"] = t
        # true ratings off the |player| lines — authoritative, unlike the JSONL
        pl = re.findall(r"\|player\|(p[12])\|([^|]*)\|[^|]*\|(\d+)", t)
        r["_true_rating"] = r["_true_opp"] = None
        for slot, who, elo in pl:
            if who == name:
                r["_true_rating"] = int(elo)
            else:
                r["_true_opp"] = int(elo)
    return rows, reps


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--jsonl", default="results/ladder/L2.battles.jsonl")
    ap.add_argument("--replays", default="results/ladder/replays")
    ap.add_argument("--name", default="nickgen1rbrlbot")
    ap.add_argument("--out", default="LADDER_R1_READOUT.md",
                    help="TRACKED path on purpose: results/ is "
                         "gitignored, so the readout must land in "
                         "the repo to survive losing results/")
    args = ap.parse_args()

    import ladder_classify as lc
    from ladder import ladder_snapshot

    rows, reps = load(args.jsonl, args.replays, args.name)
    n = len(rows)
    w = sum(1 for r in rows if r["outcome"] == "win")

    # (iii) played vs non-games, using the RATIFIED instrument
    for r in rows:
        r["_cat"] = lc.classify(r["_text"], args.name) if r["_text"] else "NO_REPLAY"
    cats = collections.Counter(r["_cat"] for r in rows)
    played = [r for r in rows if r["_cat"] != "no_show"]
    pw = sum(1 for r in played if r["outcome"] == "win")

    # (i) rating trajectory
    have_jsonl = sum(1 for r in rows if r.get("rating"))
    have_true = sum(1 for r in rows if r["_true_rating"])
    traj = [(r["index"], r["_true_rating"] or r.get("rating")) for r in rows]
    traj = [(i, v) for i, v in traj if v]

    # (ii) rematch cell
    seen, first, re_ = set(), [], []
    for r in rows:
        (re_ if r["opponent"] in seen else first).append(r)
        seen.add(r["opponent"])

    def cell(rs):
        if not rs:
            return None
        wr = sum(1 for x in rs if x["outcome"] == "win") / len(rs)
        opp = [x["_true_opp"] or x.get("opponent_rating") for x in rs]
        opp = [o for o in opp if o]
        return dict(n=len(rs), w=sum(1 for x in rs if x["outcome"] == "win"),
                    rate=wr, turns=statistics.mean(x["turns"] for x in rs),
                    opp_mean=statistics.mean(opp) if opp else None,
                    opp_med=statistics.median(opp) if opp else None,
                    opp_n=len(opp))
    fc, rc = cell(first), cell(re_)
    snap = ladder_snapshot("gen1randombattle", args.name)

    L = []
    A = L.append
    A(f"# LADDER R1 — final readout (n = {n})\n")
    A("Generated by `scripts/ladder_readout.py`. **This file is the committed")
    A("provenance for these numbers** — `results/ladder/` is gitignored, so the")
    A("JSONL and the replays are not in git and exist only on disk and in")
    A("mirrors. Everything below is reproducible by re-running that script")
    A("against those artifacts.\n")
    A("## Status of the primary read\n")
    A(f"- Profile reachable: **{snap.get('profile_ok')}**")
    A(f"- Board reachable: **{snap.get('board_ok')}**")
    A(f"- Listed on the top-500: **{snap.get('listed')}**")
    A(f"- Top-500 admission cutoff: Elo **{snap.get('cutoff_elo')}**")
    # CORRECTED 2026-08-26, and the GENERATOR was fixed 2026-08-27. This
    # block used to branch on `listed` from the TOP-500 LEADERBOARD and emit
    # "GXE AND GLICKO ARE UNMEASURED. Showdown publishes them only for
    # listed accounts. The pre-registered primary read therefore does not
    # exist for this run." **That is false.** The leaderboard JSON contains
    # only listed accounts, but the USER PROFILE
    # (https://pokemonshowdown.com/users/<userid>.json) carries GXE and
    # Glicko-1 for ANY rated account. LADDER R1 was declared unmeasurable on
    # that branch and its numbers were on the profile the whole time
    # (GXE 59.6%, Glicko-1 1573 +/- 27, Elo 1292). Being unlisted is a
    # statement about the TOP-500 BOARD, never about whether a rating exists.
    # `ladder.ladder_snapshot` now reads both sources, so the branch below
    # keys on whether a RATING exists rather than on where it is ranked.
    if snap.get("rd") is not None:
        A(f"\n**PRIMARY READ (server-computed, via "
          f"{snap.get('rating_source')}):** GXE **{snap.get('gxe')}%**, "
          f"Glicko-1 **{snap['r']:.0f} +/- {snap['rd']:.0f}**, "
          f"Elo **{snap['elo']:.0f}**, record "
          f"**{snap.get('w')}-{snap.get('l')}**.")
        A("Quoted WITH n, WITH the policy kind and WITH the board position,")
        A("exactly as pre-registered. DESCRIPTIVE — the ladder credits no")
        A("lever, and being unlisted is a fact about the board, not about")
        A("whether this rating exists.\n")
        rule = {"glicko_rd_max": 40, "min_battles": 200}
        met = (snap["rd"] <= rule["glicko_rd_max"]) and (n >= rule["min_battles"])
        A(f"- Stopping rule (`rd <= 40 AND n >= 200`): "
          f"**{'SATISFIED' if met else 'NOT satisfied'}** "
          f"at rd {snap['rd']:.1f}, n {n}.")
        A("  (R1's `L2.report.json` says `stopped_by_rule: false`. That is an")
        A("  ARTIFACT of the runner reading rd off the leaderboard it was not")
        A("  on — not a statement that the rule failed. Fixed 2026-08-27.)\n")
    elif snap.get("profile_ok") and snap.get("rated") is False:
        A("\n**NO RATING YET** — the profile is reachable and reports no")
        A("rated games in this format. A real negative, not a missing read.\n")
    else:
        A("\n**PRIMARY READ UNAVAILABLE — ENDPOINT FAILURE, NOT ABSENCE.**")
        A(f"profile_ok={snap.get('profile_ok')} "
          f"({snap.get('profile_error')}); "
          f"board_ok={snap.get('board_ok')} ({snap.get('board_error')}).")
        A("Do NOT read this as 'we have no rating' — that inversion is")
        A("exactly what cost R1 two days.\n")
    A("## Headline (all DESCRIPTIVE — the ladder credits no lever)\n")
    A("| | |")
    A("|---|---|")
    A(f"| rated battles | {n} |")
    A(f"| record | {w}–{n-w} (**{w/n:.3f}**) |")
    A(f"| played-only (ratified cut, excludes no-shows) | {pw}/{len(played)} "
      f"(**{pw/len(played):.3f}**) |")
    # EVERY VALUE IN `traj` IS A **PRE-BATTLE** RATING — verified on 195/195
    # consecutive pairs of the R1 run (sign(rating[i+1]-rating[i]) matches
    # outcome[i] 100% of the time). So `traj[-1]` is the rating going INTO
    # the last battle, not the rating after it. This generator used to label
    # it "PS Elo, final" and that is the origin of the "Elo 1311" this repo
    # quoted for two days; the true final was 1292, one loss later. The
    # PROFILE is authoritative for the final value and is used when present.
    if traj:
        if snap.get("elo") is not None:
            A(f"| PS Elo, final (profile, authoritative) | "
              f"**{snap['elo']:.0f}** |")
            A(f"| PS Elo, last PRE-battle value | {traj[-1][1]} |")
        else:
            A(f"| PS Elo, last PRE-battle value (profile unreachable — "
              f"NOT the final) | **{traj[-1][1]}** |")
        A(f"| PS Elo, highest observed (pre-battle) | "
          f"{max(v for _, v in traj)} |")
        A(f"| PS Elo, start | {traj[0][1]} |")
    A(f"| distinct opponents | {len({r['opponent'] for r in rows})} |")
    A(f"| mean turns | {statistics.mean(r['turns'] for r in rows):.1f} |")
    A("\n## Obligation (i) — rating trajectory from the replays\n")
    A(f"poke-env recorded a rating on **{have_jsonl}/{n}** battles; the replays")
    A(f"carry the server's true value on **{have_true}/{n}**. The replays are")
    A("authoritative and the JSONL column is advisory, exactly as pre-registered.\n")
    if traj:
        step = max(1, len(traj) // 20)
        A("PRE-battle Elo by battle index (every "
          f"{step}): " + " → ".join(str(v) for i, v in traj[::step]) + "\n")
        A("Every value above is the rating going INTO that battle. The final")
        A("rating is one battle later and comes from the profile, not here.\n")
    A("## Obligation (ii) — the rematch cell\n")
    A("| cell | n | W | win rate | mean turns | opp Elo mean | opp Elo median |")
    A("|---|---|---|---|---|---|---|")
    for lbl, c in (("first encounter", fc), ("rematch (2nd+)", rc)):
        if c:
            A(f"| {lbl} | {c['n']} | {c['w']} | {c['rate']:.3f} | "
              f"{c['turns']:.1f} | "
              f"{c['opp_mean']:.0f} | {c['opp_med']:.0f} |" if c["opp_mean"]
              else f"| {lbl} | {c['n']} | {c['w']} | {c['rate']:.3f} | "
                   f"{c['turns']:.1f} | — | — |")
    A("\n**Read the opponent-rating columns before the win-rate columns.**")
    A("Rematches are rating-matched by construction — opponents met twice skew")
    A("stronger — so a lower rematch win rate is predicted with zero")
    A("memorisation. This cell is descriptive and attaches to no lever.\n")
    A("## Obligation (iii) — played games vs non-games\n")
    A(f"Categories: `{dict(cats)}`\n")
    A(f"- all rated battles: **{w}/{n} = {w/n:.3f}** (reconciles with the board)")
    A(f"- played only, RATIFIED cut: **{pw}/{len(played)} = {pw/len(played):.3f}**")
    A("  (a no-show — opponent submitted zero moves — is not a game; a forfeit")
    A("  or a mid-game timeout IS a win, per the 2026-08-25 amendment)\n")
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text("\n".join(L) + "\n")
    print("\n".join(L))
    print(f"\n-> {args.out}")


if __name__ == "__main__":
    main()
