"""Search relook — the OFFLINE MARGIN CURVE (docs/search_relook/MARGIN_SELECTOR.md).

    POKEMON_RL_ENCODER_V2=1 POKEMON_RL_ENCODER_IDS=1 \
      python scripts/search_margin_curve.py \
        --prereg configs/eval/ch3_rung2.yaml --harvest results/ch3_r1 \
        --per-lane 200 --tag d26_12m --out results/search_margin

One job: replay real harvested decisions through Dose M, record the two
numbers the margin gate compares — `row_ev[a_s]` (the D4 argmax's matrix
score) and `row_ev[a_pi]` (the POLICY argmax's matrix score) — and report
the OVERRIDE RATE the gate would produce at each delta in a pre-stated grid.
Offline: no server, no battles, no websocket. PUBLIC harvest only
(harvest_<lane>.pkl, never harvest_priv_* — FG-4).

**WHAT THIS IS NOT.** Override rate is NOT win rate. R3 measured flip rate
RISING with evaluator noise while wins FELL (0.732 -> 0.480 as sigma rose,
flips 0.561 -> 0.649): flips are not wins, and neither are overrides. This
curve has exactly ONE job — choosing which deltas are worth spending
battles on. A delta whose override rate is ~0 cannot change anything (the
arm IS the greedy policy), and a delta whose override rate is ~0.73 is
just today's search (the arm IS S3M). The interesting deltas are the ones
that land strictly between, and only a LIVE screen can say which of them,
if any, wins.

WHY A NEW SCRIPT rather than a third mode in scripts/search_s1_s2_screens.py:
that script's two modes each carry a PRE-REGISTERED read rule pinned to the
shape of `s1.json` / `s2.json` (S1 FIRES / the S2 budget bound), and both
run two SearchAgent arms per decision to serve them. This needs one arm per
ENCODER and a post-hoc sweep over deltas, and it must not perturb the
meaning of either pre-registered file. The decision SAMPLE is deliberately
identical: the same `np.linspace` stride over the same non-aliased public
rows of the same four D26 lanes.

TWO OBJECTS, and the second one's caveat is the point:

  --tag d26_12m     the four D26 12M lanes, each checkpoint on its OWN
                    harvested states. Fully self-consistent.
  --tag finals_100m the three 100M finals (s104/s112/s120) replayed on the
                    SAME 12M-lane harvested states, because THERE IS NO
                    100M HARVEST and building one is NOT POSSIBLE OFFLINE:
                    rl/search/harvest.py freezes battle1 off a LIVE
                    battle, so a harvest needs a server and real games.
                    The states here were generated by a 12M policy playing
                    SimpleHeuristics; the live screen's states will be
                    generated by the 100M policy playing SimpleHeuristics.
                    That is a DECLARED DISTRIBUTION SHIFT and it is why
                    this object reads as a SHAPE, never as a number.

Both encoders run in every job: the as-is leaf encoding (what S3M ran) and
`leaf_encoding: det_blind` (DET_BLIND.md — the better encoder, which did not
move the win rate: P-B = -0.0088, NEG). Both arms key the SAME
`decision_rng`, so they draw the identical four determinizations and expand
the identical branches; they differ only in how a leaf is ENCODED.

A PLUMBING CHECK runs on the first `--check-decisions` decisions of every
checkpoint lane: the real `SearchAgent(..., margin_delta=d)` path is run at
two deltas and its action must equal the post-hoc prediction from the
recorded margin. The curve and the flag are then the same object.
"""

import argparse
import json
import os
import pickle
import time
from pathlib import Path

import numpy as np
import torch
import yaml

from rl.common.checkpoint import load_checkpoint
from rl.common.config import Config
from rl.search.agent import SearchAgent
from rl.search.harvest import rehydrate_battle
from rl.search.matrix import DOSES, SearchWatchdogError

# Pre-stated, written before the script was run. Endpoints included on
# purpose: 0.0 reproduces S3M's selector and inf reproduces A0's.
DELTA_GRID = (0.0, 0.005, 0.01, 0.02, 0.03, 0.05, 0.075, 0.1, 0.15, 0.2,
              float("inf"))
ENCODINGS = (("as_is", None), ("det_blind", "det_blind"))
# Keys the decision_rng apart when one checkpoint lane reads several state
# lanes (the finals_100m object). Zero for the first state lane, so the
# d26_12m sample keys byte-identically to the S1/S2 screens' sample.
LANE_KEY_STRIDE = 100_000
CHECK_DELTAS = (0.02, 0.1)


def _load_agent(spec: dict):
    """Exactly scripts/search_s1_s2_screens.py::_load_agent."""
    import gymnasium as gym

    from rl.envs.showdown import OBS_DIM
    from rl.train import make_agent

    ckpt = load_checkpoint(spec["path"])
    cfg = Config(**ckpt["config"])
    assert not getattr(cfg, "normalize_obs", False)
    env = gym.Env()
    env.observation_space = gym.spaces.Box(-1.0, 4.0, shape=(OBS_DIM,), dtype=np.float32)
    env.action_space = gym.spaces.Discrete(10)
    agent = make_agent(cfg, env)
    agent.load_state_dict(ckpt["agent"])
    return agent, cfg


def _pool(harvest_dir: Path, lane: str):
    with open(harvest_dir / f"harvest_{lane}.pkl", "rb") as f:
        battles = pickle.load(f)
    idx = [(bi, si) for bi, b in enumerate(battles)
           for si, row in enumerate(b["rows"]) if not row["aliased"]]
    return battles, idx


def _sample(harvest_dir: Path, state_lanes: list[str], n: int):
    """`n` decisions, split evenly across the state lanes, strided within
    each. With one state lane this is exactly the S1/S2 sample."""
    per = n // len(state_lanes)
    out, metas = [], {}
    for li, sl in enumerate(state_lanes):
        battles, idx = _pool(harvest_dir, sl)
        metas[sl] = {
            "n_episodes": len(battles),
            "n_rows_total": int(sum(len(b["rows"]) for b in battles)),
            "n_rows_nonaliased": len(idx),
            "searchable_decisions_per_battle": len(idx) / max(len(battles), 1),
            "n_sampled": per,
        }
        for k in np.linspace(0, len(idx) - 1, num=per, dtype=int):
            bi, si = idx[int(k)]
            out.append((sl, li, bi, si, battles[bi]["rows"][si]))
    return out, metas


def screen_lane(prereg: dict, lane: str, state_lanes: list[str], n: int,
                harvest_dir: Path, check_decisions: int) -> tuple[list[dict], dict]:
    agent, cfg = _load_agent(prereg["checkpoints"][lane])
    seed = int(cfg.seed)
    assert seed == int(lane.lstrip("s")), (seed, lane)
    arms = {
        name: SearchAgent(agent, DOSES["M"], checkpoint_seed=seed,
                          leaf_encoding=enc)
        for name, enc in ENCODINGS
    }
    gated = {
        d: SearchAgent(agent, DOSES["M"], checkpoint_seed=seed, margin_delta=d)
        for d in CHECK_DELTAS
    }

    sample, metas = _sample(harvest_dir, state_lanes, n)
    out, checks = [], []
    for rank, (state_lane, li, bi, si, row) in enumerate(sample):
        key_bi = bi + li * LANE_KEY_STRIDE
        rec = {
            "ckpt_lane": lane, "state_lane": state_lane,
            "episode": bi, "step": si, "turn": int(row["turn"]),
            "greedy_recorded": int(row["action"]),
            "n_legal": int(np.asarray(row["mask"]).sum()),
        }
        for name, _ in ENCODINGS:
            battle = rehydrate_battle(row["battle"])
            t0 = time.perf_counter()
            try:
                action, stats = arms[name].act(
                    battle, row["obs"], np.asarray(row["mask"]),
                    battle_index=key_bi, decision_index=si,
                )
                err = None
            except SearchWatchdogError as exc:
                action, stats, err = -1, {}, str(exc)
            rec[f"ms_{name}"] = (time.perf_counter() - t0) * 1e3
            rec[f"err_{name}"] = err
            rec[f"placeholder_skip_{name}"] = int(
                stats.get("search/placeholder_skip", 0)
            )
            rec[f"leaves_{name}"] = int(stats.get("search/leaves", 0))
            row_ev = stats.get("search/row_ev")
            if row_ev:
                # a_s is the D4 argmax with the gate OFF, i.e. `search/chosen`
                a_s = int(stats["search/chosen"])
                a_pi = int(stats["search/policy_argmax"])
                rec[f"a_s_{name}"] = a_s
                rec[f"a_pi_{name}"] = a_pi
                rec[f"ev_s_{name}"] = float(row_ev[a_s])
                rec[f"ev_pi_{name}"] = float(row_ev[a_pi])
                rec[f"margin_{name}"] = float(row_ev[a_s] - row_ev[a_pi])
                rec[f"row_ev_sd_{name}"] = float(
                    np.std([float(v) for v in row_ev.values()])
                )
            else:
                for k in ("a_s", "a_pi", "ev_s", "ev_pi", "margin", "row_ev_sd"):
                    rec[f"{k}_{name}"] = None
        out.append(rec)

        # --- plumbing check: the flag reproduces the post-hoc prediction ---
        if rank < check_decisions and rec["margin_as_is"] is not None:
            for d in CHECK_DELTAS:
                battle = rehydrate_battle(row["battle"])
                got, _ = gated[d].act(
                    battle, row["obs"], np.asarray(row["mask"]),
                    battle_index=key_bi, decision_index=si,
                )
                want = (rec["a_s_as_is"] if rec["margin_as_is"] > d
                        else rec["a_pi_as_is"])
                checks.append({
                    "ckpt_lane": lane, "state_lane": state_lane,
                    "episode": bi, "step": si, "delta": d,
                    "got": int(got), "want": int(want), "ok": int(got) == int(want),
                })

    meta = {
        "ckpt_lane": lane,
        "checkpoint_seed": seed,
        "checkpoint": prereg["checkpoints"][lane],
        "state_lanes": state_lanes,
        "state_lane_meta": metas,
        "plumbing_checks": checks,
        "plumbing_checks_passed": all(c["ok"] for c in checks),
    }
    return out, meta


# ---------------------------------------------------------------------------
# aggregation
# ---------------------------------------------------------------------------

def _curve(rows: list[dict], name: str) -> dict:
    """The delta grid for one encoder. Denominator = SEARCHED decisions,
    the same denominator the live `search/flip_rate` uses (decisions minus
    placeholder skips), so the two are directly comparable."""
    ok = [r for r in rows
          if r[f"err_{name}"] is None and not r[f"placeholder_skip_{name}"]
          and r[f"margin_{name}"] is not None]
    if not ok:
        return {"n_searched": 0}
    m = np.array([r[f"margin_{name}"] for r in ok], dtype=np.float64)
    differs = np.array([r[f"a_s_{name}"] != r[f"a_pi_{name}"] for r in ok])
    multi = np.array([r["n_legal"] > 1 for r in ok])
    grid = {}
    for d in DELTA_GRID:
        over = (m > d) & differs
        grid[repr(d)] = {
            "delta": d,
            "override_rate": float(over.mean()),
            "n_overrides": int(over.sum()),
            "override_rate_n_legal_ge_2": float(over[multi].mean()) if multi.any() else None,
        }
    marg_at_flip = m[differs]
    return {
        "n_decisions": len(rows),
        "n_searched": len(ok),
        "n_watchdog": int(sum(r[f"err_{name}"] is not None for r in rows)),
        "n_placeholder_skips": int(sum(r[f"placeholder_skip_{name}"] for r in rows)),
        "n_one_legal_action": int((~multi).sum()),
        # delta 0 is D4's own selector: this IS the offline flip rate
        "flip_rate_d4": float(differs.mean()),
        "grid": grid,
        "margin_percentiles_at_a_s_ne_a_pi": {
            p: float(np.percentile(marg_at_flip, p))
            for p in (1, 5, 10, 25, 50, 75, 90, 95, 99)
        } if marg_at_flip.size else {},
        "mean_margin_at_a_s_ne_a_pi": float(marg_at_flip.mean()) if marg_at_flip.size else None,
        "median_margin_at_a_s_ne_a_pi": float(np.median(marg_at_flip)) if marg_at_flip.size else None,
        "mean_ev_s": float(np.mean([r[f"ev_s_{name}"] for r in ok])),
        "mean_ev_pi": float(np.mean([r[f"ev_pi_{name}"] for r in ok])),
        "mean_row_ev_sd": float(np.mean([r[f"row_ev_sd_{name}"] for r in ok])),
        "leaves_per_decision": float(np.mean([r[f"leaves_{name}"] for r in ok])),
        "ms_per_decision_CONTENDED": float(np.mean([r[f"ms_{name}"] for r in ok])),
        # sanity: a_pi is the checkpoint's OWN greedy action. For the object
        # whose checkpoint generated the states this must be ~1.0; for the
        # cross-object replay it is a distribution-shift diagnostic, not a gate.
        "agreement_a_pi_vs_greedy_recorded": float(
            np.mean([r[f"a_pi_{name}"] == r["greedy_recorded"] for r in ok])
        ),
    }


def _cross_encoder(rows: list[dict]) -> dict:
    ok = [r for r in rows if r["margin_as_is"] is not None
          and r["margin_det_blind"] is not None]
    if not ok:
        return {"n": 0}
    return {
        "n": len(ok),
        "a_s_agreement": float(np.mean([r["a_s_as_is"] == r["a_s_det_blind"] for r in ok])),
        "a_pi_agreement": float(np.mean([r["a_pi_as_is"] == r["a_pi_det_blind"] for r in ok])),
        "mean_abs_margin_diff": float(np.mean(
            [abs(r["margin_as_is"] - r["margin_det_blind"]) for r in ok]
        )),
        "leaves_equal": bool(all(r["leaves_as_is"] == r["leaves_det_blind"] for r in ok)),
    }


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--prereg", default="configs/eval/ch3_rung2.yaml")
    ap.add_argument("--harvest", default="results/ch3_r1")
    ap.add_argument("--per-lane", type=int, default=200)
    ap.add_argument("--out", default="results/search_margin")
    ap.add_argument("--tag", required=True, help="d26_12m | finals_100m | ...")
    ap.add_argument("--torch-threads", type=int, default=2)
    ap.add_argument("--lanes", default="", help="checkpoint lanes; default all")
    ap.add_argument(
        "--state-lanes", default="",
        help="harvest lanes supplying the DECISIONS; default = the checkpoint "
             "lane itself (self-consistent). Naming others declares a "
             "distribution shift and the readout must say so.",
    )
    ap.add_argument("--check-decisions", type=int, default=5)
    args = ap.parse_args()

    for var in ("POKEMON_RL_ENCODER_V2", "POKEMON_RL_ENCODER_IDS"):
        assert os.environ.get(var) == "1", f"{var}=1 required (828-d D26 objects)"
    torch.set_num_threads(args.torch_threads)

    prereg = yaml.safe_load(Path(args.prereg).read_text())
    lanes = args.lanes.split(",") if args.lanes else list(prereg["checkpoints"])
    state_lanes = args.state_lanes.split(",") if args.state_lanes else None
    outdir = Path(args.out)
    outdir.mkdir(parents=True, exist_ok=True)

    rows, metas = [], {}
    t0 = time.perf_counter()
    for lane in lanes:
        sl = state_lanes or [lane]
        print(f"[{time.strftime('%H:%M:%S')}] {args.tag}: ckpt {lane} on states "
              f"{','.join(sl)} ({args.per_lane} decisions x 2 encoders)...",
              flush=True)
        lrows, meta = screen_lane(prereg, lane, sl, args.per_lane,
                                  Path(args.harvest), args.check_decisions)
        rows.extend(lrows)
        metas[lane] = meta
    wall = time.perf_counter() - t0

    checks = [c for m in metas.values() for c in m["plumbing_checks"]]
    out = {
        "screen": "MARGIN CURVE — override rate vs delta, offline",
        "read_rule": (
            "OVERRIDE RATE IS NOT WIN RATE. R3 measured flip rate RISING "
            "with evaluator noise while wins FELL, so an override rate is "
            "the SIZE of a selector's footprint, never its sign. This "
            "curve's only job is to choose which deltas a LIVE screen "
            "should spend battles on: a delta whose override rate is ~0 "
            "cannot change anything (it is the greedy policy), and a delta "
            "whose override rate is ~0.73 is just today's search."
        ),
        "provenance": {
            "tag": args.tag,
            "prereg": args.prereg,
            "harvest": args.harvest,
            "per_lane": args.per_lane,
            "ckpt_lanes": lanes,
            "state_lanes_arg": args.state_lanes or "(each checkpoint's own lane)",
            "cross_object_replay": bool(state_lanes),
            "cross_object_caveat": (
                "the checkpoints are NOT the policies that generated these "
                "states; there is no 100M harvest and building one is NOT "
                "POSSIBLE OFFLINE (rl/search/harvest.py freezes battle1 off "
                "a LIVE battle). Read the SHAPE, never the number."
            ) if state_lanes else None,
            "dose": "M",
            "n_det": DOSES["M"].n_det,
            "delta_grid": [d for d in DELTA_GRID],
            "encodings": [n for n, _ in ENCODINGS],
            "torch_threads": args.torch_threads,
            "wall_sec": wall,
            "paired_note": (
                "both encoders key the SAME decision_rng, so they draw the "
                "identical four determinizations and expand the identical "
                "branches; they differ ONLY in how a leaf is encoded"
            ),
            "lane_meta": metas,
        },
        "plumbing_check": {
            "deltas": list(CHECK_DELTAS),
            "n": len(checks),
            "all_passed": all(c["ok"] for c in checks),
            "failures": [c for c in checks if not c["ok"]],
            "what": (
                "SearchAgent(margin_delta=d).act() must return the action the "
                "recorded margin predicts; the flag and this curve are then "
                "the same object"
            ),
        },
        "pooled": {n: _curve(rows, n) for n, _ in ENCODINGS},
        "per_lane": {
            ln: {n: _curve([r for r in rows if r["ckpt_lane"] == ln], n)
                 for n, _ in ENCODINGS}
            for ln in lanes
        },
        "cross_encoder": _cross_encoder(rows),
        "decisions": rows,
    }
    path = outdir / f"margin_curve_{args.tag}.json"
    path.write_text(json.dumps(out, indent=2) + "\n")

    for enc, _ in ENCODINGS:
        c = out["pooled"][enc]
        print(f"\n{args.tag} / {enc}: n={c['n_searched']} "
              f"flip_rate(D4)={c['flip_rate_d4']:.4f}")
        for d in DELTA_GRID:
            g = c["grid"][repr(d)]
            print(f"   delta {d!r:>8}  override_rate {g['override_rate']:.4f} "
                  f"({g['n_overrides']})")
    print(f"\nplumbing check: {out['plumbing_check']['all_passed']} "
          f"({out['plumbing_check']['n']} probes)")
    print(f"wrote {path}  ({wall / 60:.1f} min)")


if __name__ == "__main__":
    main()
